# Generated by Django 4.2.3 on 2023-07-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_alter_articulo_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
